name: Lint and unit tests
description: Running lint check and unit tests for the source repo
inputs:
  python-version:
    required: true
    description: "Python version"
    default: "3.10"
  tox-version:
    required: false
    description: "Tox version, which should be used, e.g. `<4`"
    default: ""
  working-directory:
    required: false
    description: "To change working directory"
    default: "."
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
    with:
      submodules: true
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python-version }}
  - name: Install dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
      python -m pip install "tox${{ inputs.tox-version }}"
  - name: Run lint checkers
    working-directory: ${{ inputs.working-directory }}
    shell: bash
    run: tox -e lint
  - name: Run unit tests
    working-directory: ${{ inputs.working-directory }}
    shell: bash
    run: tox -e unit
  - name: Save PR number to file
    shell: bash
    run: echo ${{ github.event.number }} > PR_NUMBER.txt
  - name: Archive PR number
    uses: actions/upload-artifact@v3
    with:
      name: PR_NUMBER
      path: PR_NUMBER.txt
  - name: Archive code coverage results
    uses: actions/upload-artifact@v3
    with:
      name: coverage-report
      path: ${{ inputs.working-directory }}/tests/unit/report/coverage.xml
