name: Functional tests

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        description: "Python version"
        type: string
        default: "3.10"
      tox-version:
        required: false
        description: "Tox version, which should be used, e.g. `<4`"
        type: string
        default: ""
      working-directory:
        required: false
        description: "To change working directory"
        type: string
        default: "."
      snapcraft:
        required: false
        description: "Flag if snap is tested."
        type: boolean
        default: false
      series:
        required: false
        description: "List of series used with `tox -e func -- --series <series>`"
        type: string
        default: "['jammy']"
      # actions-operator
      provider:
        required: false
        type: string
        default: "lxd"

jobs:
  snap-func:
    name: Functional tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: true
      matrix:
        series: ${{ fromJson(inputs.series) }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: ${{ inputs.provider }}
      - name: Install snapcraft
        if: ${{ inputs.snapcraft }}
        run: sudo snap install snapcraft --classic
      - name: Run tests for `${{ matrix.series }}` series
        working-directory: ${{ inputs.working-directory }}
        run: tox -e func -- -sv --series ${{ matrix.series }}
