on:
  workflow_call:
    inputs:
      track:
        description: |
          The track to which charm should be released. By default, the latest track
          will be used.
        default: latest
        required: false
        type: string
      risk-level:
        description: |
          The risk level of the channel to which charm should be released. Valid
          inputs are: edge, beta, candidate, stable. By default, the snap will be
          released to a channel with "edge" risk level. 
        default: edge
        required: false
        type: string
  workflow_dispatch:

jobs:
  publish:
    name: Publish Snap
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: snap-artifact
      - id: get-snap-name
        run: echo "SNAP_FILE=$(ls *.snap)" >> $GITHUB_OUTPUT
      - name: Release snap to the specified channel
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.get-snap-name.outputs.SNAP_FILE }}
          release: ${{ inputs.track }}/${{ inputs.risk-level }}
