name: Pull Request

on:
  workflow_call:
    inputs:
      python-version-unit:
        required: true
        description: "Python version"
        type: string
        default: "['3.8', '3.10']"
      python-version-func:
        required: true
        description: "Python version"
        type: string
        default: "3.10"
      tox-version:
        required: false
        description: "Tox version, which should be used, e.g. `<4`"
        type: string
        default: ""
      working-directory:
        required: false
        description: "To change working directory"
        type: string
        default: "."
      snapcraft:
        required: false
        description: "Flag if snap is tested."
        type: boolean
        default: false
      timeout-minutes:
        required: false
        description: "Configurable timeout limit for functional test job"
        type: number
        default: 60
      commands:
        required: true
        description: |
          Command to run functional test in strategies. It accepts a stringified list
          of commands, which allows you to run multiple tests with different parameters.
          This is a required input field.
          Examples:
          - "['make functional']"
          - "['FUNC_ARGS="--series jammy" make functional',
             'FUNC_ARGS="--series focal" make functional']"
          - "['tox -e func -- -sv --series jammy', 'tox -e func -- -sv --series focal']"
        type: string
      # actions-operator
      provider:
        required: false
        type: string
        default: "lxd"
      nested-containers:
        required: false
        type: boolean
        default: false
      src-dir:
        required: false
        type: string
        default: "src"

jobs:
  check-changes:
    name: Check changes and previous workflow results
    runs-on: ubuntu-latest
    if: >-
      github.event_name == 'pull_request'
      || github.event.review.state == 'approved'
      || github.event.review.body == 'recheck'
    outputs:
      skip-func-tests: ${{ steps.check-skip.outputs.skip-func-tests }}
      skip-lint-unit-tests: ${{ steps.check-skip.outputs.skip-lint-unit-tests }}
    steps:
      - uses: actions/checkout@v3
      - id: check-skip
        uses: agileshaw/check-skip-test@v1
        with:
          src-dir: ${{ inputs.src-dir }}

  lint-unit:
    name: Lint checkers and unit tests
    uses: ./.github/workflows/_lint-unit.yaml
    needs:
    - check-changes
    # Note(rgildein): Lint checkers and unit tests should be triggered on any pull requested,
    # approval pull request, review was submitted or review comment with recheck.
    if: |
      needs.check-changes.outputs.skip-lint-unit-tests == 0
      || github.event.review.body == 'recheck'
    secrets: inherit
    with:
      python-version: ${{ inputs.python-version-unit }}
      tox-version: ${{ inputs.tox-version }}
      working-directory: ${{ inputs.working-directory }}

  func:
    uses: ./.github/workflows/_func.yaml
    needs:
    - lint-unit
    # Note(rgildein): Functional tests should be triggered only for commits to
    # master/main branch, if PR was approved or review comment with recheck
    if: |
      contains(fromJson('["main", "master"]'), github.ref_name) ||
      needs.check-changes.outputs.skip-func-tests == 0 ||
      github.event.review.body == 'recheck'
    secrets: inherit
    with:
      python-version: ${{ inputs.python-version-func }}
      tox-version: ${{ inputs.tox-version }}
      working-directory: ${{ inputs.working-directory }}
      timeout-minutes: ${{ inputs.timeout-minutes }}
      snapcraft: ${{ inputs.snapcraft }}
      commands: ${{ inputs.commands }}
      provider: ${{ inputs.provider }}
      nested-containers: ${{ inputs.nested-containers }}
