name: Pull Request

on:
  workflow_call:
    inputs:
      python-version-unit:
        required: true
        description: "Python version"
        type: string
        default: "['3.8', '3.10']"
      python-version-func:
        required: true
        description: "Python version"
        type: string
        default: "3.10"
      tox-version:
        required: false
        description: "Tox version, which should be used, e.g. `<4`"
        type: string
        default: ""
      working-directory:
        required: false
        description: "To change working directory"
        type: string
        default: "."
      snapcraft:
        required: false
        description: "Flag if snap is tested."
        type: boolean
        default: false
      timeout-minutes:
        required: false
        description: "Configurable timeout limit for functional test job"
        type: number
        default: 60
      commands:
        required: true
        description: |
          Command to run functional test in strategies. It accepts a stringified list
          of commands, which allows you to run multiple tests with different parameters.
          This is a required input field.
          Examples:
          - "['make functional']"
          - "['FUNC_ARGS="--series jammy" make functional',
             'FUNC_ARGS="--series focal" make functional']"
          - "['tox -e func -- -sv --series jammy', 'tox -e func -- -sv --series focal']"
        type: string
      # actions-operator
      provider:
        required: false
        type: string
        default: "lxd"
      nested-containers:
        required: false
        type: boolean
        default: false

jobs:
  lint-unit:
    name: Lint checkers and unit tests
    # Note(rgildein): Lint checkers and unit tests should be triggered on any pull requested,
    # approval pull request, review was submitted or review comment with recheck.
    if: |
      github.event_name == 'pull_request' ||
      github.event.review.state == 'approved' ||
      github.event.review.body == 'recheck'
    secrets: inherit
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}
    strategy:
      fail-fast: true
      matrix:
        command: ${{ fromJson(inputs.commands) }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
  func:
    needs: 
    - lint-unit
    # Note(rgildein): Functional tests should be triggered only for commits to
    # master/main branch, if PR was approved or review comment with recheck
    if: |
      contains(fromJson('["main", "master"]'), github.event.ref_name) ||
      github.event.review.state == 'approved' ||
      github.event.review.body == 'recheck'
    secrets: inherit
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}
    strategy:
      fail-fast: true
      matrix:
        command: ${{ fromJson(inputs.commands) }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
