name: Pull Request

on:
  workflow_call:
    inputs:
      python-version-unit:
        required: true
        description: "Python version"
        type: string
        default: "['3.8', '3.10']"
      python-version-func:
        required: true
        description: "Python version"
        type: string
        default: "3.10"
      tox-version:
        required: false
        description: "Tox version, which should be used, e.g. `<4`"
        type: string
        default: ""
      working-directory:
        required: false
        description: "To change working directory"
        type: string
        default: "."
      snapcraft:
        required: false
        description: "Flag if snap is tested."
        type: boolean
        default: false
      timeout-minutes:
        required: false
        description: "Configurable timeout limit for functional test job"
        type: number
        default: 60
      commands:
        required: true
        description: |
          Command to run functional test in strategies. It accepts a stringified list
          of commands, which allows you to run multiple tests with different parameters.
          This is a required input field.
          Examples:
          - "['make functional']"
          - "['FUNC_ARGS="--series jammy" make functional',
             'FUNC_ARGS="--series focal" make functional']"
          - "['tox -e func -- -sv --series jammy', 'tox -e func -- -sv --series focal']"
        type: string
      # actions-operator
      provider:
        required: false
        type: string
        default: "lxd"
      nested-containers:
        required: false
        type: boolean
        default: false

jobs:
  lint-unit:
    name: Lint checkers and unit tests
    secrets: inherit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(inputs.python-version) }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install "tox${{ inputs.tox-version }}"
    - name: Run lint checkers
      working-directory: ${{ inputs.working-directory }}
      run: tox -e lint
    - name: Run unit tests
      working-directory: ${{ inputs.working-directory }}
      run: tox -e unit
    - name: Save PR number to file
      run: echo ${{ github.event.number }} > PR_NUMBER.txt
    - name: Archive PR number
      uses: actions/upload-artifact@v3
      with:
        name: PR_NUMBER
        path: PR_NUMBER.txt
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: ${{ inputs.working-directory }}/tests/unit/report/coverage.xml

  func:
    needs:
    - lint-unit
    name: Functional tests
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}
    strategy:
      fail-fast: true
      matrix:
        command: ${{ fromJson(inputs.commands) }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install "tox${{ inputs.tox-version }}"
      - name: Setup Juju environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: ${{ inputs.provider }}
      - name: Remove tox install by actions-operator
        run: sudo apt remove tox -y
      - name: Install snapcraft
        if: ${{ inputs.snapcraft }}
        run: sudo snap install snapcraft --classic
      - name: Enabled nested LXD containers
        if: ${{ inputs.provider == 'lxd' && inputs.nested-containers }}
        run: |
          # create new lxd project and configure nesting & privileged
          lxc profile show default > default-lxc-profile.yaml
          lxc project create nested-lxd
          lxc profile edit --project nested-lxd default < default-lxc-profile.yaml
          lxc profile set --project nested-lxd default security.nesting=true
          lxc profile set --project nested-lxd default security.privileged=true
          # set default project to be nested-lxd project
          juju model-default project=nested-lxd
      - name: Run tests with `${{ matrix.command }}`
        working-directory: ${{ inputs.working-directory }}
        run: ${{ matrix.command }}
