name: Lint checkers and Unit tests


on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  lint-unit:
    uses: ./.github/workflows/lint_unit.yaml
    secrets: inherit
    with:
      charm-path: ${{ inputs.charm-path }}
