name: Test for func workflow

on:
  push:
    branches: [ master, main ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master, main ]

jobs:
  charm-func:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: true
      matrix:
        command: ['FUNC_ARGS=\"--series jammy\" make functional']
    steps:
    - name: Running functional tests for the charm source repo
      uses: ./.github/actions/func-test
      with:
        python-version: "3.10"
        tox-version: "<4"
        working-directory: ./tests/test_charm_repo
        command: ${{ matrix.command }}
        provider: "lxd"
        nested-containers: true

  snap-func:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
    - name: Running functional tests for the snap source repo
      uses: ./.github/actions/func-test
      with:
        python-version: "3.10"
        tox-version: "<4"
        working-directory: ./tests/test_snap_repo
        snapcraft: true
