name: Test for func workflow


on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  charm-lint-unit:
    uses: ./.github/workflows/func.yaml
    secrets: inherit
    with:
      python-version: "3.10"
      tox-version: "<4"
      working-directory: ./tests/test_charm_repo
      posargs: --series jammy

  snap-lint-unit:
    uses: ./.github/workflows/func.yaml
    secrets: inherit
    with:
      python-version: "3.10"
      tox-version: "<4"
      working-directory: ./tests/test_snap_repo
      snap: true
