name: Tests for lint-unit workflow

on:
  push:
    branches: [ master, main ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master, main ]

jobs:
  charm-lint-unit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8','3.10']
    steps:
    - name: Running lint check and unit tests for the charm source repo
      uses: ./.github/actions/lint-unit-test
      with:
        python-version: ${{ matrix.python-version }}
        tox-version: "<4"
        working-directory: ./tests/test_charm_repo

  snap-lint-unit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8','3.10']
    steps:
    - name: Running lint check and unit tests for the snap source repo
      uses: ./.github/actions/lint-unit-test
      with:
        python-version: ${{ matrix.python-version }}
        tox-version: "<4"
        working-directory: ./tests/test_snap_repo
