name: Lint checkers and Unit tests


on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  charm-lint-unit:
    uses: ./.github/workflows/_lint-unit.yaml
    secrets: inherit
    with:
      python-version: "3.10"
      tox-version: "<4"
      working-directory: ./tests/test_charm_repo

  snap-lint-unit:
    uses: ./.github/workflows/_lint-unit.yaml
    secrets: inherit
    with:
      python-version: "3.10"
      tox-version: "<4"
      working-directory: ./tests/test_snap_repo
