name: Test for func workflow


on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  charm-func:
    uses: ./.github/workflows/_func.yaml
    secrets: inherit
    with:
      python-version: "3.10"
      tox-version: "<4"
      working-directory: ./tests/test_charm_repo
      series: "['jammy']"

  snap-func:
    uses: ./.github/workflows/_func.yaml
    secrets: inherit
    with:
      python-version: "3.10"
      tox-version: "<4"
      working-directory: ./tests/test_snap_repo
      snapcraft: true
