name: SonarCloud
on:
  workflow_run:
    workflows: 
      - Test for PR workflow
    types: [completed]

jobs:
  sonar:
    uses: ./.github/workflows/sonar.yaml
    secrets: inherit
    with:
      workflow-name: Test for PR workflow
